mm:
  ports:
    config: 8001
    gateway: 8002
    eureka: 8761

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://mmahu-main:8761/eureka/