mm:
  ports:
    gateway: 7070
    eureka: 8761
    config: 8001

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://mmahu-main:8761/eureka/