hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  client:
    serviceUrl:
      defaultZone: http://master:8761/eureka/