server:
  port: 9090

spring:
  cloud:
    gateway:
      default-filters:
        - SaveSession
        - StripPrefix=2
        - RemoveRequestHeader=Set-Cookie
        - RemoveResponseHeader=Set-Cookie
      routes:
        - id: account
          uri: lb://e-account
          predicates:
            - Path=/api/account/**